### PR TITLE
Кочин - Лабораторная работа #1

### PR DESCRIPTION
**Pull request by ivankochin**

### CODE REVIEW

**Comment by ivankochin** [comment]
Excuse me, mark my work please .
@kirill-korniakov

**Comment by ivankochin** [comment]
Guys, I need your opinion about my code, if you liked it, write :+1: in the comments 

Criticism is welcome 

@DmitrichevNick 
@sith228 
@Olegka35 
@Marat-Israfilov

**Comment by VinogradovaE** [comment]
:+1:

**Comment by lemurtaison** [comment]
:+1:

**Pull request merged**
