### PR TITLE
Kulygina julia lab3

### PR DESCRIPTION
**Pull request by KulyginaJulia**

### CODE REVIEW

**Comment by KulyginaJulia** [comment]
@IlyaKiparenko
@Anna-Mironova
@SemenBevzuk

**Comment by IlyaKiparenko** [comment]
:+1:

**Comment by SemenBevzuk** [comment]
👍

**Comment by Anna-Mironova** [comment]
👍

**Comment by KulyginaJulia** [comment]
@kirill-korniakov

**Comment by KulyginaJulia** [comment]
@LebedevIlyaG

**Pull request merged**
